#pragma once
#ifndef MODULE_CONFIG_INTERNAL_H
#define MODULE_CONFIG_INTERNAL_H

#include <ModuleConfig.h>

//Check if all required macros if defined:
#ifndef USE_INTEL_SGX_ENCLAVE
#error "USE_INTEL_SGX_ENCLAVE must be defined!"
#endif // !USE_INTEL_SGX_ENCLAVE
#ifndef USE_DECENTRALIZED_ENCLAVE
#error "USE_DECENTRALIZED_ENCLAVE must be defined!"
#endif // !USE_DECENTRALIZED_ENCLAVE
#ifndef USE_DECENT_ENCLAVE
#error "USE_DECENT_ENCLAVE must be defined!"
#endif // !USE_DECENT_ENCLAVE
#ifndef USE_DECENT_ENCLAVE_SERVER
#error "USE_DECENT_ENCLAVE_SERVER must be defined!"
#endif // !USE_DECENT_ENCLAVE_SERVER
#ifndef USE_DECENT_ENCLAVE_APP
#error "USE_DECENT_ENCLAVE_APP must be defined!"
#endif // !USE_DECENT_ENCLAVE_APP


#if USE_INTEL_SGX_ENCLAVE
#	define USE_INTEL_SGX_ENCLAVE_INTERNAL 1
#else
#	define USE_INTEL_SGX_ENCLAVE_INTERNAL 0
#endif // USE_INTEL_SGX_ENCLAVE

#if !USE_DECENTRALIZED_ENCLAVE || (!USE_INTEL_SGX_ENCLAVE_INTERNAL)
#	define USE_DECENTRALIZED_ENCLAVE_INTERNAL 0
#else
#	define USE_DECENTRALIZED_ENCLAVE_INTERNAL 1
#endif //!USE_DECENTRALIZED_ENCLAVE || (!USE_INTEL_SGX_ENCLAVE_INTERNAL)

#if !USE_DECENT_ENCLAVE || (!USE_INTEL_SGX_ENCLAVE_INTERNAL)
#	define USE_DECENT_ENCLAVE_INTERNAL 0
#else
#	define USE_DECENT_ENCLAVE_INTERNAL 1
#endif //!USE_DECENT_ENCLAVE || (!USE_INTEL_SGX_ENCLAVE_INTERNAL)

#if !USE_DECENT_ENCLAVE_SERVER || !USE_DECENT_ENCLAVE_INTERNAL
#	define USE_DECENT_ENCLAVE_SERVER_INTERNAL 0
#else
#	define USE_DECENT_ENCLAVE_SERVER_INTERNAL 1
#endif //!USE_DECENT_ENCLAVE_SERVER || !USE_DECENT_ENCLAVE_INTERNAL

#if !USE_DECENT_ENCLAVE_APP || !USE_DECENT_ENCLAVE_INTERNAL
#	define USE_DECENT_ENCLAVE_APP_INTERNAL 0
#else
#	define USE_DECENT_ENCLAVE_APP_INTERNAL 1
#endif //!USE_DECENT_ENCLAVE_APP || !USE_DECENT_ENCLAVE_INTERNAL

#endif // !MODULE_CONFIG_INTERNAL_H
